tap "homebrew/bundle"
tap "homebrew/services"
tap "mongodb/brew"
brew "gettext"
brew "glib"
brew "coreutils"
brew "docker-compose"
brew "unbound", restart_service: :changed
brew "gnutls"
brew "harfbuzz"
brew "srt"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "helix", args: ["HEAD"]
brew "imagemagick"
brew "mas"
brew "mise"
brew "pkgconf"
brew "poppler"
brew "postgresql@16", restart_service: :changed
brew "rabbitmq", restart_service: :changed
brew "rclone"
brew "rsync"
brew "rust"
brew "scc"
brew "mongodb/brew/mongodb-community@5.0"
cask "android-platform-tools"
cask "android-studio"
cask "audacity"
cask "beekeeper-studio"
cask "blackhole-2ch"
cask "boop"
cask "browserstacklocal"
cask "caffeine"
cask "cyberduck"
cask "docker"
cask "elektron-transfer"
cask "figma"
cask "firefox@developer-edition"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-ibm-plex"
cask "font-open-sans"
cask "font-roboto"
cask "fork"
cask "ghostty"
cask "google-chrome"
cask "gpg-suite"
cask "handbrake"
cask "imageoptim"
cask "inkscape"
cask "jdownloader"
cask "jellyfin-media-player"
cask "karabiner-elements"
cask "keybase"
cask "keycastr"
cask "kitty"
cask "libreoffice"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mullvadvpn"
cask "ngrok"
cask "obs"
cask "openemu"
cask "pd"
cask "postman"
cask "scratch"
cask "skype"
cask "slack"
cask "soulseek"
cask "sync"
cask "the-unarchiver"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "vuescan"
cask "zoom"
mas "iMovie", id: 408981434
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835
vscode "arcticicestudio.nord-visual-studio-code"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "jasew.vscode-helix-emulation"
vscode "redhat.java"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-maven"
vscode "youmaycallmev.vscode-java-saber"
