tap "homebrew/bundle"
tap "homebrew/services"
tap "mongodb/brew"
brew "gettext"
brew "glib"
brew "cloc"
brew "coreutils"
brew "unbound", restart_service: true
brew "gnutls"
brew "harfbuzz"
brew "srt"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "helix"
brew "imagemagick"
brew "mas"
brew "mise"
brew "neovim"
brew "postgresql@16", restart_service: true
brew "rabbitmq", restart_service: true
brew "rclone"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "serve"
brew "stylua"
brew "zellij"
brew "mongodb/brew/mongodb-community@5.0"
cask "audacity"
cask "beekeeper-studio"
cask "blackhole-2ch"
cask "boop"
cask "browserstacklocal"
cask "caffeine"
cask "cyberduck"
cask "docker"
cask "elektron-transfer"
cask "figma"
cask "firefox@developer-edition"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-fira-sans"
cask "font-ibm-plex"
cask "font-open-sans"
cask "font-roboto"
cask "fork"
cask "google-chrome"
cask "gpg-suite"
cask "graphql-playground"
cask "handbrake"
cask "imageoptim"
cask "inkscape"
cask "jdownloader"
cask "jellyfin-media-player"
cask "karabiner-elements"
cask "keybase"
cask "keycastr"
cask "kitty"
cask "libreoffice"
cask "macwhisper"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-teams"
cask "mullvadvpn"
cask "musicbrainz-picard"
cask "ngrok"
cask "obs"
cask "openemu"
cask "pd"
cask "postman"
cask "skype"
cask "slack"
cask "soulseek"
cask "steam"
cask "sync"
cask "the-unarchiver"
cask "tinymediamanager"
cask "transmission"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "vuescan"
cask "zoom"
mas "iMovie", id: 408981434
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
vscode "arcticicestudio.nord-visual-studio-code"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "koichisasada.vscode-rdbg"
vscode "redhat.java"
vscode "shopify.ruby-extensions-pack"
vscode "shopify.ruby-lsp"
vscode "sorbet.sorbet-vscode-extension"
vscode "tomwhite007.rename-angular-component"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-maven"
vscode "vscodevim.vim"
vscode "youmaycallmev.vscode-java-saber"
