tap "codeclimate/formulae"
tap "helix-editor/helix"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
brew "coreutils"
brew "libtool"
brew "asdf"
brew "gettext"
brew "glib"
brew "cloc"
brew "openldap"
brew "curl"
brew "unbound", restart_service: true
brew "gnutls"
brew "harfbuzz"
brew "srt"
brew "ffmpeg"
brew "gcc"
brew "fzf"
brew "git-crypt"
brew "helix"
brew "node"
brew "http-server"
brew "imagemagick"
brew "mas"
brew "neovim"
brew "openjdk"
brew "prettier"
brew "rclone"
brew "restic"
brew "ripgrep"
brew "stylua"
brew "vips"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
cask "1password6"
cask "audacity"
cask "blackhole-2ch"
cask "boop"
cask "browserstacklocal"
cask "caffeine"
cask "cyberduck"
cask "docker"
cask "elektron-transfer"
cask "figma"
cask "firefox-developer-edition"
cask "fork"
cask "google-chrome"
cask "gpg-suite"
cask "graphql-playground"
cask "handbrake"
cask "imageoptim"
cask "inkscape"
cask "intellij-idea-ce"
cask "jdownloader"
cask "karabiner-elements"
cask "keybase"
cask "kitty"
cask "mattermost"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-teams"
cask "ngrok"
cask "nordvpn"
cask "openemu"
cask "pd"
cask "playdate-simulator"
cask "postman"
cask "skype"
cask "slack"
cask "soulseek"
cask "steam"
cask "the-unarchiver"
cask "transmission"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zoom"
mas "iMovie", id: 408981434
mas "Key Codes", id: 414568915
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Excel", id: 462058435
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
