allow_remote_control yes
listen_on unix:/tmp/kitty

enabled_layouts fat, stack
draw_minimal_borders yes
window_padding_width 5
hide_window_decorations yes 
confirm_os_window_close 1

map shift+insert paste_from_clipboard
map ctrl+insert copy_to_clipboard

tab_bar_edge bottom
tab_bar_style separator
tab_separator ""
tab_title_template "  {index}  "
active_tab_font_style   bold

map cmd+t             new_tab_with_cwd

# BEGIN_KITTY_FONTS
font_family      family="Fira Mono"
bold_font        "Fira Mono Medium"
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 12
modify_font cell_height 16px

include nord.conf

