font=Fira Code:size=12
font-bold=Fira Code Semibold:size=12
line-height=22
pad=10x10

[csd]
size=0

[colors-dark]
foreground=d8dee9  # Nord4 (Snow Storm)
background=2e3440  # Nord0 (Polar Night)

# Regular colors
regular0=3b4252   # Nord1 (Polar Night)
regular1=bf616a   # Nord11 (Aurora Red)
regular2=a3be8c   # Nord14 (Aurora Green)
regular3=ebcb8b   # Nord13 (Aurora Yellow)
regular4=81a1c1   # Nord9 (Frost Blue)
regular5=b48ead   # Nord15 (Aurora Purple)
regular6=88c0d0   # Nord8 (Frost Cyan)
regular7=e5e9f0   # Nord5 (Snow Storm)

# Bright colors
bright0=4c566a    # Nord3 (Polar Night)
bright1=bf616a    # Nord11 (Aurora Red)
bright2=a3be8c    # Nord14 (Aurora Green)
bright3=ebcb8b    # Nord13 (Aurora Yellow)
bright4=81a1c1    # Nord9 (Frost Blue)
bright5=b48ead    # Nord15 (Aurora Purple)
bright6=8fbcbb    # Nord7 (Frost Cyan)
bright7=eceff4    # Nord6 (Snow Storm)

