[[snippets]]
prefix = "log"
scope = [ "javascript", "typescript", "javascriptreact", "typescriptreact" ]
body = "console.log(${1:$TM_SELECTED_TEXT});"

[[snippets]]
prefix = "us"
scope = [ "javascript", "typescript", "javascriptreact", "typescriptreact" ]
body = "const [$1, set${1/(.*)/${1:/capitalize}/}] = useState($2);"

[[snippets]]
prefix = "inj"
scope = [ "javascript", "typescript" ]
body = "${1} = inject(${1/(.*)/${1:/pascalcase}/});"


