theme = "nord"

[editor]
rulers = [80]
default-yank-register = "+"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
esc = ["collapse_selection", "keep_primary_selection"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

[keys.select]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[keys.normal."space"]
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "global_search"]
"f" = "file_picker_in_current_directory"
"<" = "file_picker_in_current_buffer_directory"

