[language-server.angular]
command = "ngserver"
scope = "source.angular"
roots = ["angular.json"]
args = [ "--stdio", "--tsProbeLocations", "$(yarn global dir)/node_modules", "--ngProbeLocations", "$(yarn global dir)/node_modules" ]
file-types = ["ts", "html"]

[[language]]
name = "html"
auto-format = true
language-servers = ["vscode-html-language-server", "angular"]
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "eslint"]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "vue"
formatter = { command = 'prettier', args = ["--parser", "vue"] }
auto-format = true

