[tools]
node = "22.12.0"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:prettier" = "latest"
"npm:stylelint-lsp" = "latest"
"npm:vscode-langservers-extracted" = "4.8.0"
"npm:@astrojs/language-server" = "latest"
"npm:@angular/language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@volar/vue-language-service" = "latest"
"npm:graphql-language-service" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:corepack" = "latest"
usage = "latest"
tinymist = "latest"
"github:tontinton/maki" = "latest"

[settings]
activate_aggressive = true
idiomatic_version_file_enable_tools = ["ruby", "node"]

[settings.ruby]
compile = false
